language: cpp
compiler: gcc
dist: trusty

before_install:
    # C++ 11
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    
install:
    # C++ 11
    - sudo apt-get install -qq g++-5
    - sudo update-alternatives --install /usr/bin/g++ usr/bin/g++-5 90
    
script:
    - g++ ./Hackerrank/array-left-rotation.cpp -std=c++11 -o travis_gcc_cpp11
    - ./travis_gcc_cpp11

